Imported Upstream version 0.9.2

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #!/bin/sh
-# This script was automatically generated by ACR v0.8.6
+# This script was automatically generated by ACR v0.9.1
 # @author: pancake <youterm.com>
 # @url:    http://www.nopcode.org
 # @repo:   hg clone http://hg.youterm.com/acr
@@ -17,11 +17,13 @@ control_c() {
   exit 1
 }
 trap control_c 2
+CPARSE=0
 DEBUGGER=1
 USE_MAGIC=0
 HAVE_EWF=1
 HAVE_GMP=1
 HAVE_OPENSSL=1
+USE_RPATH=0
 HAVE_LILEND=0
 HAVE_BIGEND=0
 [ -z "${USERCC}" ] && USERCC="gcc"
@@ -101,15 +103,16 @@ done
 : ${INSTALL_DIR:=${INSTALL} -d}
 : ${INSTALL_DATA:=${INSTALL} -m 644}
 : ${INSTALL_SCRIPT:=${INSTALL} -m 755}
-: ${INSTALL_PROGRAM:=${INSTALL} -m 755 -s}
+: ${INSTALL_PROGRAM:=${INSTALL} -m 755}
+: ${INSTALL_PROGRAM_STRIP:=${INSTALL} -m 755 -s}
 : ${INSTALL_MAN:=${INSTALL} -m 444}
 : ${INSTALL_LIB:=${INSTALL} -c}
- PKGNAME='radare2' ; VERSION='0.9' ; CONTACT_MAIL="pancake@nopcode.org" ; CONTACT_NAME="pancake" ; CONTACT="pancake <pancake@nopcode.org>" ;
+ PKGNAME='radare2' ; VERSION='0.9.2' ; CONTACT_MAIL="pancake@nopcode.org" ; CONTACT_NAME="pancake" ; CONTACT="pancake <pancake@nopcode.org>" ;
 }
                 
 show_usage() {
 cat <<EOF2
-'configure' configures radare2-0.9 to adapt to many kinds of systems.
+'configure' configures radare2-0.9.2 to adapt to many kinds of systems.
 
 Usage: ./configure [OPTION]... [VAR=VALUE]...
 
@@ -147,28 +150,36 @@ System types:
   --target=TARGET        configure for building compilers for TARGET [HOST]
 EOF2
 
-printf "\nOptional Features:
-  --without-debugger     disable native debugger features 
+printf "
+Optional Features:
+  --enable-cparse        build with cparse support 
+  --disable-debugger     disable native debugger features 
   --with-sysmagic        force to use system's magic 
   --without-ewf          disable EWF dependency 
   --without-gmp          disable GMP dependency 
   --without-ssl          disable openssl dependency 
+  --with-rpath           use rpath to build 
   --with-little-endian   force little endian 
   --with-big-endian      force big endian 
   --with-compiler        Define compiler to use (see mk/)  (USERCC=gcc)
   --with-ostype          Choose OS type ( gnulinux windows darwin )  (USEROSTYPE=auto)
   --without-pic          do not build libr as a program independent location 
   --with-nonpic          build the library archives .a 
-  --with-libversion      specify different libversion  (LIBVERSION=xxx)\n"
-printf "\nSome influential environment variables:
+  --with-libversion      specify different libversion  (LIBVERSION=xxx)
+"
+printf "
+Some influential environment variables:
   CC          C compiler command
   CFLAGS      C compiler flags
+  CPPFLAGS    C preprocessor flags
   LDFLAGS     linker flags, e.g. -L<lib dir> if you have libraries in a
               nonstandard directory <lib dir>
   CPPFLAGS    C/C++ preprocessor flags, e.g. -I<include dir> if you have
               headers in a nonstandard directory <include dir>
-  CPP         C preprocessor\n"
-printf "\nReport bugs to: pancake <pancake@nopcode.org>"
+  CPP         C preprocessor
+"
+printf "
+Report bugs to: pancake <pancake@nopcode.org>"
 echo ""
 exit 0
 }
@@ -181,7 +192,7 @@ take_environ() {
 }
 
 show_version() {
-echo "radare2-0.9 configuration script done with acr v0.8.6.
+echo "radare2-0.9.2 configuration script done with acr v0.9.1.
 The 'Free Software Foundation' message is only for autodetection.
 Originally written by pancake <youterm.com>."
 exit 0
@@ -192,6 +203,12 @@ flag=`echo $1| cut -d = -f 1`
 value=`echo $1| awk 'BEGIN{FS="=";}{print $2}'`
 flag2=`echo $flag|cut -f2- -d -| sed -e 's,-,_,g' -e 's,^_,,g'|tr '[a-z]' '[A-Z]'`
 
+if [ "${TARGET_OS}" = "darwin" ]; then
+	LIBPATH=-Wl,-install_name,
+else
+	LIBPATH=-Wl,-R
+fi
+
 case $flag in
 "-h"|"--help"|"--hel"|"--h"|"--he"|"-help")
 	show_usage ; ;;
@@ -199,12 +216,12 @@ case $flag in
 	show_version ; ;;
 "-r"|"--r"|"--report")
 echo "PKGNAME:   radare2"
-echo "VERSION:   0.9"
+echo "VERSION:   0.9.2"
 echo "LANGS:     c"
 echo "REQUIRED:  libdl"
 echo "OPTIONAL:  libmagic"
-echo "PKG-CONFIG:  openssl"
-echo "FLAGS:     --without-debugger --with-sysmagic --without-ewf --without-gmp --without-ssl --with-little-endian --with-big-endian --with-compiler=gcc --with-ostype=auto --without-pic --with-nonpic --with-libversion=xxx"
+echo "PKG-CONFIG:  libewf openssl"
+echo "FLAGS:     --enable-cparse --disable-debugger --with-sysmagic --without-ewf --without-gmp --without-ssl --with-rpath --with-little-endian --with-big-endian --with-compiler=gcc --with-ostype=auto --without-pic --with-nonpic --with-libversion=xxx"
 	exit 0
 	;;
 "--cache-file") 
@@ -238,7 +255,7 @@ echo "FLAGS:     --without-debugger --with-sysmagic --without-ewf --without-gmp 
 "--localstatedir")
 	LOCALSTATEDIR="$value"; ;;
 "--libdir")
-	LIBDIR="$value"; LDFLAGS="${LDFLAGS} -L$value -Wl,-R$value"; ;;
+	LIBDIR="$value"; LDFLAGS="${LDFLAGS} -L$value ${LIBPATH}$value"; ;;
 "--includedir")
 	INCLUDEDIR="$value"; CFLAGS="${CFLAGS} -I$value"; ;;
 "--infodir")
@@ -246,11 +263,13 @@ echo "FLAGS:     --without-debugger --with-sysmagic --without-ewf --without-gmp 
 "--mandir")
 	MANDIR="$value"; ;;
 
-"--without-debugger") DEBUGGER="0"; ;;
+"--enable-cparse") CPARSE="1"; ;;
+"--disable-debugger") DEBUGGER="0"; ;;
 "--with-sysmagic") USE_MAGIC="1"; ;;
 "--without-ewf") HAVE_EWF="0"; ;;
 "--without-gmp") HAVE_GMP="0"; ;;
 "--without-ssl") HAVE_OPENSSL="0"; ;;
+"--with-rpath") USE_RPATH="1"; ;;
 "--with-little-endian") HAVE_LILEND="1"; ;;
 "--with-big-endian") HAVE_BIGEND="1"; ;;
 --with-compiler) if [ -z "${value}" ]; then USERCC="gcc"; else USERCC="${value}" ; fi ;;
@@ -275,7 +294,7 @@ parse_options $1
 shift
 done
 
-ENVWORDS="MANDIR INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR SYSCONFDIR DATADIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU PKGNAME VPATH VERSION CONTACT CONTACT_NAME CONTACT_MAIL CC CFLAGS LDFLAGS HAVE_LANG_C DEBUGGER HAVE_LIB_DL DL_LIBS LIL_ENDIAN BIG_ENDIAN BYTEORDER HAVE_LIB_MAGIC USE_MAGIC USE_LIB_MAGIC LIBMAGIC HAVE_LIB_EWF HAVE_EWF HAVE_LIB_GMP HAVE_GMP HAVE_LIB_SSL SSL_CFLAGS SSL_LDFLAGS HAVE_PKGCFG_OPENSSL HAVE_OPENSSL HAVE_LILEND HAVE_BIGEND HAVE_LIB_LUA5_1 HAVE_LIB_TCC USERCC USEROSTYPE WITHPIC WITHNONPIC LIBVERSION"
+ENVWORDS="MANDIR INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR SYSCONFDIR DATADIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_PROGRAM_STRIP INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU PKGNAME VPATH VERSION CONTACT CONTACT_NAME CONTACT_MAIL CC CFLAGS CPPFLAGS LDFLAGS HAVE_LANG_C CPARSE DEBUGGER HAVE_LIB_DL DL_LIBS LIL_ENDIAN BIG_ENDIAN BYTEORDER HAVE_LIB_MAGIC USE_MAGIC USE_LIB_MAGIC LIBMAGIC HAVE_FLEX FLEX HAVE_LIB_EWF EWF_CFLAGS EWF_LDFLAGS HAVE_PKGCFG_LIBEWF HAVE_EWF HAVE_LIB_GMP HAVE_GMP HAVE_LIB_SSL SSL_CFLAGS SSL_LDFLAGS HAVE_PKGCFG_OPENSSL HAVE_OPENSSL USE_RPATH HAVE_LILEND HAVE_BIGEND HAVE_LIB_LUA5_1 HAVE_LIB_TCC USERCC USEROSTYPE WITHPIC WITHNONPIC LIBVERSION"
 
 create_environ
 
@@ -300,7 +319,7 @@ if [ "${CROSSBUILD}" = 1 ]; then
  if [ $? = 0 ]; then CC="${HOST}-${CC}"; fi
 fi
 echo "main(){}" > test.c
- (exec ${CC} ${CFLAGS} ${LDFLAGS} test.c >/dev/null 2>&1)
+ (exec ${CC} ${CFLAGS} ${CPPFLAGS} ${LDFLAGS} test.c >/dev/null 2>&1)
 if [ $? = 0 ]; then echo ${CC}; else
  echo no ; HAVE_LANG_C=0
 do_remove
@@ -342,7 +361,7 @@ _CHKLIB_NAME=$2
 _CHKLIB_LIBS=$(echo "-l${_CHKLIB_NAME}" | sed 's,\+, -l,g')
 printf "checking for lib${_CHKLIB_NAME} ... "
 echo "main(){ }" > test.c
-eval ${S}${COMPILER} ${CFLAGS} ${CXXFLAGS} ${LDFLAGS} ${_CHKLIB_LIBS} test.c >/dev/null 2>&1
+eval ${S}${COMPILER} ${CFLAGS} ${CPPFLAGS} ${CXXFLAGS} ${LDFLAGS} ${_CHKLIB_LIBS} test.c >/dev/null 2>&1
 if [ $? = 0 ]; then
 	eval ${VAR}=1
 	echo yes
@@ -357,7 +376,42 @@ LIBMAGIC="-lmagic"
 else
 USE_LIB_MAGIC="0"
 LIBMAGIC="-lr_magic"; fi
+printf "checking for flex... "
+if [ -x "${FLEX}" ]; then
+	FIND=${FLEX}
+else
+	FIND=""
+	for A in `echo ${PATH} | sed -e 's,:, ,g'`; do
+		if [ -x "${A}/flex" ]; then
+			FIND="${A}/flex"
+			break;
+		fi
+	done
+fi
+if [ -n "${FIND}" ]; then 
+	echo ${FIND}; 
+HAVE_FLEX=1
+	FLEX=${FIND}
+else
+	HAVE_FLEX=0
+	FLEX=flex
+echo no
+	echo "error: This program is required." >&2
+	exit 1 ; fi
 check_library HAVE_LIB_EWF ewf 0 
+printf 'checking pkg-config flags for libewf... '
+tmp=`pkg-config --cflags libewf 2>/dev/null`
+if [ '!' $? = 0 ]; then echo no ; HAVE_PKGCFG_LIBEWF=0; 
+else 
+EWF_CFLAGS=$tmp; 
+tmp=`pkg-config --libs libewf 2>/dev/null`
+if [ $? = 0 ]; then 
+echo yes; HAVE_PKGCFG_LIBEWF=1; 
+EWF_LDFLAGS=$tmp; fi; fi
+if [ "$HAVE_PKGCFG_LIBEWF" = "1" ]; then
+HAVE_LIB_EWF="1"
+else
+HAVE_LIB_EWF="0"; fi
 if [ "$HAVE_EWF" = "0" ]; then
 HAVE_LIB_EWF="0"; fi
 check_library HAVE_LIB_GMP gmp 0 
@@ -366,11 +420,11 @@ HAVE_LIB_GMP="0"; fi
 check_library HAVE_LIB_SSL ssl 0 
 printf 'checking pkg-config flags for openssl... '
 tmp=`pkg-config --cflags openssl 2>/dev/null`
-if [ $? = 1 ]; then echo no ; HAVE_PKGCFG_OPENSSL=0; 
+if [ '!' $? = 0 ]; then echo no ; HAVE_PKGCFG_OPENSSL=0; 
 else 
 SSL_CFLAGS=$tmp; 
 tmp=`pkg-config --libs openssl 2>/dev/null`
-if [ ! $? = 1 ]; then 
+if [ $? = 0 ]; then 
 echo yes; HAVE_PKGCFG_OPENSSL=1; 
 SSL_LDFLAGS=$tmp; fi; fi
 if [ "$SSL_LDFLAGS" = "" ]; then
@@ -449,7 +503,7 @@ if [ -n "`grep \"${MARK}\" ${SD_TARGET}.tmp`" ]; then
 fi
 done
  mv ${SD_TARGET}.tmp ${SD_TARGET} && rm -f ${SD_TARGET}.tmp2
- if [ $? = 1 ]; then echo Cannot write target file ; control_c ; fi
+ if [ ! $? = 0 ]; then echo Cannot write target file ; control_c ; fi
 done
 
 do_remove
